[package]
name = "move_an_asset"
version = "1.0.0"
authors = []

[addresses]
move_asset = "0x2c9e1d3a09f7744c0fd5ddad355890d11b5d687dfd55bc75c487f6a28bad8ae8"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
